#! /bin/sh
### BEGIN INIT INFO
# Provides:          brcm40183-patch
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Should-Start:      brcm_patchram_plus
# Default-Start:     S
# Default-Stop:      
# Short-Description: Patch firmware for brcm40183 Bluetooth adapter
# Description:       Patch firmware for brcm40183 Bluetooth adapter
### END INIT INFO

DEFAULTS="/etc/default/brcm40183"

# Include brcm40183 defaults if available
if [ -r "${DEFAULTS}" ]
then
	. "${DEFAULTS}"
fi

. /lib/lsb/init-functions

do_start () {

if [ ! -z $(/usr/sbin/hciconfig | /bin/grep UART | /usr/bin/cut -d: -f1) ]
then
    /bin/echo "Info: brcm40183 device allready initialized:"
    /usr/bin/hcitool dev
else
    # Select MAC address
    if [ -z "$MAC_ADDR" ]; then
       echo "Warning: No MAC_ADDR set in /etc/default/brcm40183, will use MAC 11:22:33:44:55:66"
       MAC_OPTIONS="--bd_addr 11:22:33:44:55:66"
    else
       MAC_OPTIONS="--bd_addr $MAC_ADDR"
    fi

    # Select tty port
    if [ -z "$PORT" ]; then
       echo "Warning: No PORT set in /etc/default/brcm40183, will use ttyS1"
       PORT="ttyS1"
    fi

    # Start patching
    /bin/echo -en "" > /dev/$PORT      # pull down RTS on UART
    /bin/echo -en "Info: Start pushing firmware to device and waiting max. 60sec to complete ... "

    /usr/bin/timeout 60s /usr/local/bin/brcm_patchram_plus -d --patchram /lib/firmware/ap6210/bcm20710a1.hcd --enable_hci --no2bytes --tosleep 1000 $MAC_OPTIONS /dev/$PORT > /var/log/brcm40183.firmware 2>&1

    if [ $? -ne 0 ]
    then
         /bin/echo "terminated!"
         /bin/echo "Error: Check /var/log/brcm40183.firmware for messages."
         exit 1
    else
         /bin/echo "finished."

         # Enable interfaces
         /usr/sbin/hciattach /dev/$PORT any

    fi
fi
}

case "$1" in
  start)
	do_start
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	# No-op
	;;
  status)
	/usr/bin/hcitool dev
	;;
  *)
	echo "Usage: brcm40183-patch.sh [start|stop|status]" >&2
	exit 3
	;;
esac

